<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>bf21650d-d496-4156-90da-af2161e487a7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AspireCrud.Function/AspireCrud_Function.csproj" />
    <ProjectReference Include="..\AspireCrud.ApiService\AspireCrud.ApiService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.1.0" />
  </ItemGroup>

</Project>
